import type { Metadata } from "next";
export const metadata: Metadata = { title: "Audio Fingerprint Test — AudioContext Fingerprinting", description: "Test your audio fingerprint generated by the AudioContext API. See how websites use audio processing to identify your device.", alternates: { canonical: "https://browserprobe.app/tools/audio-fingerprint" } };
export default function Layout({ children }: { children: React.ReactNode }) { return children; }
